version: 0.1.{build}
image: Visual Studio 2019
install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt nacl.net.snk.enc -secret %SNK_SECRET% -salt %SNK_SALT%
  - sh: ./appveyor-tools/secure-file -decrypt path-to/encrypted-filename.ext.enc -secret $SNK_SECRET -salt $SNK_SALT

build_script:
- cmd: >-
    dotnet build . /p:Configuration=Release /p:PackageVersion=%APPVEYOR_BUILD_VERSION%-pre /p:Version=%APPVEYOR_BUILD_VERSION% /verbosity:minimal

    dotnet pack NaCl.net -c Release --no-build /p:PackageVersion=%APPVEYOR_BUILD_VERSION%-pre /p:Version=%APPVEYOR_BUILD_VERSION%
test_script:
- cmd: dotnet test NaCl.net.Tests
artifacts:
- path: '**/*.nupkg'
